### ISSUE TITLE
linux_arm missing

### ISSUE THREAD

**Issue by e2002e** [armory3d/armsdk#65]
the file .gitmodule in Kha is missing the linux_arm repo, which is needed by armory.py.
I have tried adding the module but even though it says that it's extracting it, the files don't appear in the Tools folder.
I also tried removing linux_arm from the sdk path in armory.py but it's still looking for linux_arm.

**Comment by luboslenco** [comment]
Hm, looks like that one is no longer included as a submodule after https://github.com/Kode/Kha/commit/cb8d9c424c9c0323c748d2c20cfbf48ac48939d8.

**Comment by e2002e** [comment]
I tried deleting the lines refering linux_arm in armory.py but it still
asks for it. Maybe the armory.py file is cached by blender ?

Le mar. 11 juil. 2023 13:28, Lubos Lenco ***@***.***> a
écrit :

**Comment by MoritzBrueckner** [comment]
In the Kha repository there is a `get_dlc` bash script that will likely download this submodule. If I recall correctly Robert did this to reduce the size of the repository so people don't have to waste disk space with submodules they don't need. Maybe we should call this script in Armory every time the SDK path changes? We could maybe even reduce the download size this way, there is also a `get_dlc.bat` for Windows for example.

> I tried deleting the lines refering linux_arm in armory.py but it still
asks for it. Maybe the armory.py file is cached by blender ?

Blender creates a copy of addon when they are installed, and since Armory is techically a one-file addon (only armory.py which dynamically loads the SDK) this means that Blender copies armory.py but no other armory file (that's why editing other files works). You can either re-install Armory (which will remove all your settings), replace the copy manually or you can enable `Developer Settings > Symlink armory.py` in the Armory preferences which will automatically keep the Blender copy of armory.py up to date.

**Comment by e2002e** [comment]
Ok, I had to reinstall armory after modifying armory.py.
Symlinking doesn't update armory.py once it's already installed, and get_dlc did not do anything.

**Comment by luboslenco** [comment]
Should be resolved thanks to https://github.com/armory3d/armsdk/pull/66.
